# Generated by Django 5.1.4 on 2025-02-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_billingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
